### ISSUE TITLE
看到你的项目，即兴发挥了一下

### ISSUE THREAD

**Issue by Toserk1024** [Kaede221/Moe-Counter-Json#1]
看到你的项目，正好网上也没有json+php的版本，我也即兴爆肝了8小时写了一个：[项目地址](https://github.com/Toserk1024/moe-counter-php)(σ≧︎▽︎≦︎)σ。

**Comment by Kaede221** [comment]
很高兴收到你的邮件！也很高兴你能浏览我的项目！
很厉害！还请继续加油！₍˄·͈༝·͈˄*₎◞ ̑̑

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Toserk ***@***.***>
Sent: Tuesday, February 13, 2024 8:50:08 PM
To: Kaede221/Moe-Counter-Json ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Kaede221/Moe-Counter-Json] 看到你的项目，即兴发挥了一下 (Issue #1)


看到你的项目，正好网上也没有json+php的版本，我也即兴爆肝了8小时，写了一个php+json的版本：项目地址<https://github.com/Toserk1024/moe-counter-php>(σ≧︎▽︎≦︎)σ。
